# Generated by Django 2.2 on 2020-05-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigngenerator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocker',
            name='duedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
